name: tirbushona_loyalty_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/banner.png
    - assets/images/brands_cloud.png
    - assets/images/billa-logo.png
    - assets/images/metro-logo.png
    - assets/images/lidl-logo.png
    - assets/images/sportdepo-logo.png
    - assets/images/kaufland-logo.png
    - assets/images/ikea-logo.png
    - assets/images/komsed-logo.png
    - assets/images/omv-logo.png
    - assets/images/medea-logo.png
    - assets/images/teodor-logo.png